image: Visual Studio 2017

configuration: Release

before_build:
  - nuget restore
  - dotnet restore

environment:
  base_version: '1.1.0'
  version_suffix: ''

version: $(base_version).{build}$(version_suffix)

dotnet_csproj:
  patch: true
  file: 'src\RazorHtmlMinifier.Mvc5\*.csproj'
  version: '$(base_version)$(version_suffix)'
  assembly_version: '$(base_version)'
  file_version: '$(base_version).{build}'

build:
  parallel: true
  verbosity: minimal

artifacts:
  - path: src\RazorHtmlMinifier.Mvc5\bin\%configuration%\*.nupkg
